# Generated by Django 3.0.1 on 2020-03-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='users_default.jpg', upload_to='user_photo'),
        ),
    ]
