# Generated by Django 3.0.1 on 2020-03-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0004_auto_20200308_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('products', models.ManyToManyField(blank=True, to='index.Product')),
            ],
        ),
    ]
