# Generated by Django 3.0.1 on 2020-03-22 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20200321_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cartitems',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.Cart'),
            preserve_default=False,
        ),
    ]
