# Generated by Django 3.0.1 on 2020-03-22 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_auto_20200322_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
    ]
