# Generated by Django 3.0.1 on 2020-03-22 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_auto_20200322_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cartitems',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Cart'),
        ),
    ]
