# Generated by Django 3.0.1 on 2020-03-22 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200308_1157'),
        ('cart', '0019_auto_20200322_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Product'),
        ),
    ]
