# Generated by Django 3.0.1 on 2020-03-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0027_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
