# Generated by Django 3.0.1 on 2020-04-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200308_1157'),
        ('cart', '0029_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='index.Product'),
        ),
    ]
