# Generated by Django 3.0.1 on 2020-04-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0031_auto_20200404_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='itemtotal',
            field=models.IntegerField(null=True),
        ),
    ]
